Repository MUTUAL-DE-SERVICIOS-AL-POLICIA/DIGITAL-KIOSK, pull requests merged in 2024-12, with the labels that each got.

#113 Adicionar un video en la pantalla de descanso del Software de Punto de Consulta de Trámites
  src/components/Video.tsx
  src/views/auth/HomeScreen.tsx
Labels: enhancement

#115 Integración de APIs para la creación de trámites de Complemento Econó…
  src/hooks/useEconomicComplementStore.ts
  src/store/ecoCom/ecoComSlice.ts
  src/store/index.ts
  src/store/store.ts
  src/views/content/economicComplement/EconomicComplementView.tsx
  src/views/content/menu.tsx
Labels: enhancement

#116 Integración de la nueva API para el guardado de la fotografía del rostro y del carnet
  package.json
  src/App.tsx
  src/hooks/useCredentialStore.ts
  src/views/auth/face/FaceRecognition.tsx
  src/views/auth/ocr/OcrRecognition.tsx
Labels: enhancement

#118 Bug de reconocimiento de rostro y guardado de fotografía
  src/components/CardInfo.tsx
  src/components/ImageCapture.tsx
  src/hooks/useChooserStore.tsx
  src/views/auth/Auth.tsx
  src/views/auth/AuthMethodChooser.tsx
  src/views/auth/Chooser.tsx
  src/views/auth/IdentityCard.tsx
  src/views/auth/InstructionCard.tsx
  src/views/auth/biometric/BiometricRecognition.tsx
Labels: bug

#121 Ajuste de recuadros del OCR y correción de reconocimiento OCR de una imagen
  src/components/ImageCapture.tsx
  src/views/auth/ocr/OcrRecognition.tsx
Labels: enhancement

#124 Mostrando en la interfaz de usuario las huellas registradas disponibles
  src/hooks/useBiometric.ts
  src/views/auth/HomeScreen.tsx
  src/views/auth/biometric/BiometricRecognition.tsx
  src/views/auth/biometric/Fingerprint.tsx
Labels: enhancement

#127 Implementación de dialogos para el reconocmiento facial, biometrico
  src/hooks/useContributionStore.ts
  src/hooks/useLoanStore.ts
  src/hooks/useSweetAlert.ts
  src/views/auth/HomeScreen.tsx
  src/views/auth/biometric/BiometricRecognition.tsx
  src/views/auth/face/FaceRecognition.tsx
  src/views/auth/ocr/OcrRecognition.tsx
  src/views/auth/styles.css
  src/views/content/contributions/ContributionView.tsx
  src/views/content/economicComplement/EconomicComplementView.tsx
  src/views/content/loans/LoanView.tsx
Labels: enhancement, refactoring

#129 Cambiando la pantalla de carga al realizar el reconocimiento de huella
  src/assets/images/fingerprint.gif
  src/views/auth/IdentityCard.tsx
  src/views/auth/biometric/BiometricRecognition.tsx
Labels: refactoring

#131 Agregando deshabilitación de huellas, si no tiene registradas ninguna
  src/components/CardMethodChooser.tsx
  src/views/auth/AuthMethodChooser.tsx
Labels: enhancement, refactoring

#132 Modificaciones menores
  src/assets/images/face.png
  src/assets/images/finger.png
  src/assets/images/fingerprint.jpg
  src/components/CardChooser.tsx
  src/components/CardMethodChooser.tsx
  src/components/ImageCapture.tsx
  src/views/auth/AuthMethodChooser.tsx
  src/views/auth/Chooser.tsx
  src/views/auth/InstructionCard.tsx
  src/views/auth/face/FaceRecognition.tsx
  src/views/auth/ocr/OcrRecognition.tsx
Labels: enhancement

#133 Cambios en forma y funcionalidad
  src/components/CardChooser.tsx
  src/components/CardMethodChooser.tsx
  src/hooks/useContributionStore.ts
  src/hooks/useEconomicComplementStore.ts
  src/store/ecoCom/ecoComSlice.ts
  src/store/store.ts
  src/views/auth/AuthMethodChooser.tsx
  src/views/content/MainView.tsx
  src/views/content/contributions/ContributionView.tsx
  src/views/content/economicComplement/EconomicComplementView.tsx
Labels: bug, enhancement, refactoring
