Repository MUTUAL-DE-SERVICIOS-AL-POLICIA/DIGITAL-KIOSK, pull requests merged in 2024-11, with the labels that each got.

#76 Implementación de pantalla de selección de servicio
  src/components/CardChooser.tsx
  src/hooks/useChooserStore.tsx
  src/store/chooser/chooserSlice.ts
  src/store/index.ts
  src/store/store.ts
  src/views/auth/Auth.tsx
  src/views/auth/Chooser.tsx
  src/views/auth/HomeScreen.tsx
Labels: enhancement, refactoring

#78 Refactorización del Layout general del proyecto
  src/components/Footer.tsx
  src/components/Header.tsx
  src/views/content/MainView.tsx
Labels: refactoring

#81 Agregando el hook useAuthStore
  src/hooks/useAuthStore.ts
Labels: enhancement

#85 Cambios temporales
  .env.example
  src/App.tsx
  src/assets/images/face.png
  src/assets/images/fingerprint.jpg
  src/assets/images/hands.png
  src/components/ImageCapture2.tsx
  src/context/LoadingContext.tsx
  src/helpers/getEnvVariables.ts
  src/hooks/useBiometric.ts
  src/hooks/useLoading.tsx
  src/services/coffeApi.ts
  src/store/biometric/fingerprintSlice.ts
  src/views/auth/biometric/BiometricRecognition.tsx
  src/views/auth/biometric/Fingerprint.tsx
Labels: enhancement

#86 Agregando lógica inversa en el reconocimiento de palabras similares
  src/views/auth/recognition/OcrRecognition.tsx
Labels: enhancement, refactoring

#87 Cambios de enfoque
  src/views/auth/recognition/FaceRecognition.tsx
  src/views/auth/recognition/OcrRecognition.tsx
Labels: enhancement

#89 Agregando validación de longitud de cadena reconocida por el OCR
  src/views/auth/recognition/OcrRecognition.tsx
Labels: enhancement, refactoring

#91 Comparación de huellas implementado en el kiosco digital
  src/helpers/getEnvVariables.ts
  src/hooks/useBiometric.ts
  src/hooks/usePersonStore.ts
  src/services/coffeApi.ts
  src/store/index.ts
  src/store/person/personSlice.ts
  src/store/store.ts
  src/views/auth/Auth.tsx
  src/views/auth/AuthMethodChooser.tsx
  src/views/auth/Chooser.tsx
  src/views/auth/biometric/BiometricRecognition.tsx
  src/views/auth/recognition/OcrRecognition.tsx
Labels: bug, enhancement, refactoring

#93 Agregando validación de huellas existentes
  src/hooks/useBiometric.ts
  src/views/auth/AuthMethodChooser.tsx
  src/views/auth/biometric/BiometricRecognition.tsx
Labels: enhancement, refactoring

#95 Arreglando bug de obtención de huellas registradas
  src/store/biometric/fingerprintSlice.ts
Labels: bug

#97 Comparación biométrica implementada
  src/hooks/useBiometric.ts
  src/views/auth/biometric/BiometricRecognition.tsx
  src/views/content/loans/styles.css
Labels: enhancement

#98 modificaciones a la comparación de huellas
  src/hooks/useBiometric.ts
  src/views/auth/biometric/BiometricRecognition.tsx
Labels: enhancement, refactoring

#100 Reestructuración y preparación de código para la vista de creación de trámites de CE
  src/hooks/usePersonStore.ts
  src/views/auth/Chooser.tsx
  src/views/content/MainView.tsx
  src/views/content/contributions/ContributionView.tsx
  src/views/content/loans/LoanView.tsx
  src/views/content/menu.tsx
Labels: refactoring

#102 Diseño UI para la creación de trámites de complemento
  src/views/content/EconomicComplement/EconomicComplementView.tsx
  src/views/content/MainView.tsx
  src/views/content/menu.tsx
Labels: enhancement

#103 Añadido opción reconocer ocr y facial mediante foto, y formato
  .env.example
  src/helpers/getEnvVariables.ts
  src/views/auth/recognition/FaceRecognition.tsx
  src/views/auth/recognition/OcrRecognition.tsx
Labels: enhancement

#105 Configurando servicio para consumir del backend PVT-BE
  .env.example
  src/helpers/getEnvVariables.ts
  src/services/coffeApi.ts
Labels: enhancement

#109 Actualizar la lógica del OCR para procesar y reconocer texto en cada cuadro de forma individual.
  src/components/ImageCapture.tsx
  src/services/coffeApi.ts
  src/views/auth/ocr/OcrRecognition.tsx
Labels: enhancement, refactoring

#111 Optimización y configuraciones generales en los componentes y vistas
  src/components/Alphanumeric.tsx
  src/components/Button.tsx
  src/components/Card.tsx
  src/components/CardChooser.tsx
  src/components/CardInfo.tsx
  src/components/CardMethodChooser.tsx
  src/components/Footer.tsx
  src/components/Header.tsx
  src/components/ImageCanvas.tsx
  src/components/ImageCapture.tsx
  src/components/index.css
  src/components/index.ts
  src/components/keyboardAlphanumeric.tsx
  src/hooks/useAuthStore.ts
  src/hooks/useBiometric.ts
  src/hooks/useEconomicComplementStore.ts
  src/main.tsx
  src/views/auth/AuthMethodChooser.tsx
  src/views/auth/Chooser.tsx
  src/views/auth/IdentityCard.tsx
  src/views/auth/InstructionCard.tsx
  src/views/auth/biometric/BiometricRecognition.tsx
  src/views/auth/biometric/Fingerprint.tsx
  src/views/auth/face/FaceRecognition.tsx
  src/views/auth/ocr/OcrRecognition.tsx
  src/views/content/MainView.tsx
  src/views/content/contributions/ContributionView.tsx
  src/views/content/economicComplement/EconomicComplementView.tsx
  src/views/content/loans/LoanView.tsx
  src/views/content/menu.tsx
Labels: enhancement, refactoring
