Repository MUTUAL-DE-SERVICIOS-AL-POLICIA/DIGITAL-KIOSK, pull requests merged in 2024-02, with the labels that each got.

#15 Implementación de teclado
  package.json
  src/components/index.css
  src/components/index.ts
  src/components/keyboard.tsx
  src/components/keyboardAlphanumeric.tsx
  src/components/keyboardNumeric.tsx
  src/views/auth/IdentityCard.tsx
  src/views/auth/InstructionCard.tsx
  src/views/auth/recognition/Recognition.tsx
  src/views/loans/CardLoan.tsx
Labels: enhancement, refactoring

#16 modificand estilos y el tiempo del temporizador
  src/components/Button.tsx
  src/components/index.css
  src/components/keyboardAlphanumeric.tsx
  src/components/keyboardNumeric.tsx
  src/views/auth/Auth.tsx
  src/views/auth/recognition/OcrView.tsx
  src/views/auth/recognition/Recognition.tsx
  src/views/loans/CardLoan.tsx
  src/views/loans/LoanView.tsx
  src/views/loans/styles.css
Labels: enhancement

#17 Agregando loading al momento de la impresión
  src/hooks/useLoanStore.ts
  src/views/auth/recognition/OcrView.tsx
  src/views/loans/CardLoan.tsx
  src/views/loans/LoanView.tsx
  src/views/loans/styles.css
Labels: enhancement

#18 Adicionando modales de respuesta la momento de la impresión
  src/hooks/useAuthStore.ts
  src/hooks/useLoanStore.ts
  src/views/auth/IdentityCard.tsx
  src/views/auth/recognition/Recognition.tsx
  src/views/loans/LoanView.tsx
Labels: enhancement

#19 OCR o reconocimiento logica implementada
  src/assets/images/PlanDePagos.png
  src/components/index.css
  src/hooks/useAuthStore.ts
  src/views/auth/InstructionCard.tsx
  src/views/auth/recognition/FaceRecognition.tsx
  src/views/auth/recognition/OcrView.tsx
  src/views/auth/recognition/Recognition.tsx
  src/views/loans/CardLoan.tsx
  src/views/loans/LoanView.tsx
Labels: enhancement, refactoring

#21 arreglando bug de ocr o reconocimiento facial
  src/views/auth/recognition/FaceRecognition.tsx
  src/views/auth/recognition/OcrView.tsx
  src/views/auth/recognition/Recognition.tsx
Labels: refactoring

#23 Modificando las cámaras para la visualización en sistema operativo Ub…
  src/views/auth/recognition/FaceRecognition.tsx
Labels: refactoring

#25 Modificaciones para las validacione de 'ci y foto' o 'nombre y foto'
  src/hooks/useAuthStore.ts
  src/hooks/useCredentialStore.ts
  src/store/auth/authSlice.ts
  src/views/auth/recognition/FaceRecognition.tsx
  src/views/auth/recognition/OcrView.tsx
  src/views/auth/recognition/Recognition.tsx
Labels: refactoring

#27 Reconocimiento de texto a partir de una imagen segmentandola en 3 par…
  src/components/ImageCapture.tsx
Labels: enhancement, refactoring

#30 Quitando código innecesario
  src/components/Footer.tsx
  src/components/ImageCapture.tsx
  src/helpers/getEnvVariables.ts
  src/hooks/useAuthStore.ts
  src/hooks/useCredentialStore.ts
  src/store/auth/authSlice.ts
  src/views/auth/Auth.tsx
  src/views/auth/recognition/FaceRecognition.tsx
  src/views/auth/recognition/OcrRecognition.tsx
  src/views/auth/recognition/OcrView.tsx
  src/views/auth/recognition/PreviousRecognition.tsx
  src/views/auth/recognition/Recognition.tsx
  src/views/auth/recognition/index.ts
  src/views/loans/LoanView.tsx
Labels: refactoring

#33 Agregando boton para retornar
  src/components/Footer.tsx
  src/components/ImageCanvas.tsx
  src/components/ImageCapture.tsx
  src/components/keyboardNumeric.tsx
  src/hooks/useAuthStore.ts
  src/views/auth/Auth.tsx
  src/views/auth/recognition/FaceRecognition.tsx
  src/views/auth/recognition/OcrRecognition.tsx
  src/views/auth/recognition/PreviousRecognition.tsx
  src/views/loans/LoanView.tsx
Labels: enhancement, refactoring

#35 Modificaciones de diseño y dando solución a las observaciones realizadas
  src/components/Button.tsx
  src/components/Footer.tsx
  src/components/index.css
  src/hooks/useAuthStore.ts
  src/hooks/useLoanStore.ts
  src/views/auth/Auth.tsx
  src/views/auth/IdentityCard.tsx
  src/views/auth/InstructionCard.tsx
  src/views/auth/recognition/FaceRecognition.tsx
  src/views/auth/recognition/OcrRecognition.tsx
  src/views/auth/recognition/PreviousRecognition.tsx
  src/views/auth/recognition/styles.css
  src/views/loans/LoanView.tsx
Labels: bug, refactoring

#36 Cambiando el orden de los números en el teclado numérico
  src/components/index.css
  src/components/keyboardNumeric.tsx
  src/views/auth/recognition/FaceRecognition.tsx
Labels: refactoring

#37 Agregando MAC al .env
  .env.example
  src/helpers/getEnvVariables.ts
  src/hooks/useAuthStore.ts
Labels: refactoring

#38 Agregando README y cambiando disposición de los números en el teclado…
  README.md
  src/components/index.css
  src/components/keyboardNumeric.tsx
Labels: refactoring

#40 Registro de estadísticas implementado
  src/components/ImageCapture.tsx
  src/hooks/index.ts
  src/hooks/useAuthStore.ts
  src/hooks/useStatisticsStore.ts
  src/store/index.ts
  src/store/statistics/statisticsSlice.ts
  src/store/store.ts
  src/views/auth/recognition/FaceRecognition.tsx
  src/views/auth/recognition/OcrRecognition.tsx
Labels: enhancement

#42 Dockerización del proyecto
  dockerfile
  nginx.conf
  vite.config.ts
Labels: enhancement

#43 Limpiando código para dockerizar
  .env.example
  .eslintrc.cjs
  src/components/Button.tsx
  src/components/ImageCapture.tsx
  src/components/keyboardAlphanumeric.tsx
  src/components/keyboardNumeric.tsx
  src/helpers/getEnvVariables.ts
  src/hooks/useAuthStore.ts
  src/hooks/useLoanStore.ts
  src/main.tsx
  src/views/auth/Auth.tsx
  src/views/auth/HomeScreen.tsx
  src/views/auth/IdentityCard.tsx
  src/views/auth/InstructionCard.tsx
  src/views/auth/recognition/FaceRecognition.tsx
  src/views/auth/recognition/OcrRecognition.tsx
  src/views/auth/recognition/PreviousRecognition.tsx
  src/views/loans/CardLoan.tsx
Labels: refactoring

#44 Optimización de componentes
  src/components/Footer.tsx
  src/hooks/useAuthStore.ts
  src/views/auth/Auth.tsx
  src/views/auth/HomeScreen.tsx
  src/views/auth/IdentityCard.tsx
  src/views/auth/InstructionCard.tsx
  src/views/auth/recognition/FaceRecognition.tsx
  src/views/auth/recognition/OcrRecognition.tsx
  src/views/auth/recognition/PreviousRecognition.tsx
Labels: refactoring

#46 Agregando reglas al linter
  .eslintrc.cjs
  src/components/ImageCapture.tsx
  src/views/auth/IdentityCard.tsx
Labels: refactoring

#48 Implementación de impresión de certificaciones de aportes como activo y pasivo
  src/assets/images/contribution.png
  src/components/Card.tsx
  src/components/ImageCapture.tsx
  src/components/Tab.tsx
  src/components/index.ts
  src/context/TimerContext.tsx
  src/helpers/index.ts
  src/helpers/utils.ts
  src/hooks/useAuthStore.ts
  src/hooks/useContributionStore.ts
  src/hooks/useLoanStore.ts
  src/router/AppRouter.tsx
  src/store/contribution/contributionSlice.ts
  src/store/index.ts
  src/store/store.ts
  src/views/auth/Auth.tsx
  src/views/auth/IdentityCard.tsx
  src/views/auth/recognition/FaceRecognition.tsx
  src/views/auth/recognition/OcrRecognition.tsx
  src/views/content/MainView.tsx
  src/views/content/contributions/ContributionView.tsx
  src/views/content/index.ts
  src/views/content/loans/LoanView.tsx
  src/views/content/loans/styles.css
  src/views/loans/LoanView.tsx
Labels: enhancement

#49 Actualización del README para el despliegue de la app con docker
  README.md
Labels: enhancement
