Repository MUTUAL-DE-SERVICIOS-AL-POLICIA/DIGITAL-KIOSK, pull requests merged in 2025-01, with the labels that each got.

#135 Agregando visualización de trámites creados
  src/hooks/useEconomicComplementStore.ts
  src/store/ecoCom/ecoComSlice.ts
  src/store/store.ts
  src/views/content/economicComplement/EconomicComplementView.tsx
Labels: enhancement

#136 Corrigiendo bug de visualización de Complemento Económico que no corr…
  src/hooks/useEconomicComplementStore.ts
  src/views/content/economicComplement/EconomicComplementView.tsx
Labels: bug

#137 Se corrigieron datos en cache
  src/hooks/useEconomicComplementStore.ts
  src/store/ecoCom/ecoComSlice.ts
  src/store/index.ts
  src/store/store.ts
  src/views/auth/Auth.tsx
  src/views/content/economicComplement/EconomicComplementView.tsx
Labels: bug

#138 Despliegue con docker compose
  README.md
  docker-compose.yml
  dockerfile
Labels: refactoring
